# Generated by Django 4.2.7 on 2024-02-25 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileWriter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer_pseudo', models.CharField(default='User-24077846 Author', max_length=100)),
                ('subscribers_counter', models.PositiveBigIntegerField(default=0)),
                ('total_likes_counter', models.PositiveBigIntegerField(default=0)),
                ('total_story_views_counter', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileReader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_stories_viewed', models.PositiveBigIntegerField(default=0)),
                ('total_comments_made', models.PositiveBigIntegerField(default=0)),
                ('total_liked_comments', models.PositiveBigIntegerField(default=0)),
                ('subscribed_to', models.ManyToManyField(to='Authentication.userprofilewriter')),
            ],
        ),
        migrations.CreateModel(
            name='BaseUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='avatars/default.jpg', upload_to='avatars/')),
                ('displayable_name', models.CharField(default='User-62372629', max_length=20)),
                ('is_premium', models.BooleanField(default=False)),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Authentication.userprofilereader')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Authentication.userprofilewriter')),
            ],
        ),
    ]
