# Generated by Django 4.2.7 on 2024-02-26 22:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilereader',
            name='subscribed_to',
        ),
        migrations.AlterField(
            model_name='baseuserprofile',
            name='displayable_name',
            field=models.CharField(default='User-94373608', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofilewriter',
            name='writer_pseudo',
            field=models.CharField(default='User-87739981 Author', max_length=100),
        ),
        migrations.CreateModel(
            name='SubscriptionTimeStampThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when_subscribed', models.DateTimeField(default=django.utils.timezone.now)),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.userprofilereader')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.userprofilewriter')),
            ],
        ),
    ]
