# Generated by Django 4.2.7 on 2024-02-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_remove_userprofilereader_subscribed_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilereader',
            name='subscribed_to',
            field=models.ManyToManyField(through='Authentication.SubscriptionTimeStampThrough', to='Authentication.userprofilewriter'),
        ),
        migrations.AlterField(
            model_name='baseuserprofile',
            name='displayable_name',
            field=models.CharField(default='User-45599171', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofilewriter',
            name='writer_pseudo',
            field=models.CharField(default='User-36025407 Author', max_length=100),
        ),
    ]
