# Generated by Django 4.2.7 on 2024-02-26 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_userprofilereader_subscribed_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontimestampthrough',
            name='receive_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='baseuserprofile',
            name='displayable_name',
            field=models.CharField(default='User-51084310', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofilewriter',
            name='writer_pseudo',
            field=models.CharField(default='User-31367868 Author', max_length=100),
        ),
    ]
