# Generated by Django 4.2.7 on 2024-02-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_subscriptiontimestampthrough_receive_notifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuserprofile',
            name='displayable_name',
            field=models.CharField(default='User-61323825', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofilewriter',
            name='writer_pseudo',
            field=models.CharField(default='User-14189048 Author', max_length=100),
        ),
    ]
