# Generated by Django 4.2.7 on 2024-02-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0010_alter_baseuserprofile_displayable_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuserprofile',
            name='displayable_name',
            field=models.CharField(default='User-60478391', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofilewriter',
            name='writer_pseudo',
            field=models.CharField(default='User-51959223 Author', max_length=100),
        ),
    ]
