version: "3.8"
services:
  frontend:
    build:
      context: ./it-management-course-front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend

  backend:
    build:
      context: ./Notifications-System
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - backend_data:/app
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=*

volumes:
  backend_data:
