# Generated by Django 4.2.7 on 2024-02-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stories', '0002_alter_post_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views_counter',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
