# Generated by Django 4.2.7 on 2024-02-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stories', '0003_post_views_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='Stories.posttags'),
        ),
    ]
