# Generated by Django 4.2.7 on 2024-02-28 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stories', '0004_remove_post_tags_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttags',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
