# Generated by Django 4.2.7 on 2024-02-22 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0003_remove_usercommentrepliednotification_reply_comment'),
        ('Comments', '0002_comment_replies_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Comments.comment'),
        ),
        migrations.DeleteModel(
            name='CommentReply',
        ),
    ]
