# Generated by Django 4.2.7 on 2024-02-27 22:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0002_remove_comment_replies_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 27, 22, 10, 29, 417823, tzinfo=datetime.timezone.utc)),
        ),
    ]
