# Generated by Django 4.2.7 on 2024-02-22 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0003_comment_parent_comment_delete_commentreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 23, 0, 8, 34, 301215)),
        ),
    ]
