# Generated by Django 4.2.7 on 2024-02-27 22:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0004_alter_comment_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 27, 22, 15, 53, 996999, tzinfo=datetime.timezone.utc)),
        ),
    ]
