# Generated by Django 4.2.7 on 2024-02-20 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeOverallNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_title', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('expiration', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserStoryCommentedNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.IntegerField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comments.comment')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stories.post')),
            ],
        ),
        migrations.CreateModel(
            name='UserCommentRepliedNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.IntegerField()),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stories.post')),
                ('reply_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comments.commentreply')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comments.comment')),
            ],
        ),
    ]
