# Generated by Django 4.2.7 on 2024-02-20 23:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativeoverallnotifications',
            name='expiration',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
