# Generated by Django 4.2.7 on 2024-02-22 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0002_alter_administrativeoverallnotifications_expiration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercommentrepliednotification',
            name='reply_comment',
        ),
    ]
